final List<String> Worktype = [
  'Private Company',
  'Government / Public Sector',
  'Defense / Civil Services',
  'Business / Self Employed',
  'Not Working',
];

String selectedWorkType ='';

final List<String> WorkAs = [
  'Android App / UI developer',
  'Android App / UX developer',
  'Software Developer / Programmer',
  'Mechanical / Production Engineer',
  'Software Consultant',
  'Software Professional(Others)',
  'Civil Engineer',
  'Non IT Engineer (Others)',
  'Electronics / Telecom Engineer',
  'Lawyer',
  'Dentist',
  'Doctor',
  'Nurse',
  'Pharmacist',
  'Surgeon',
  'Naval Officer',
  'Sales Professional',
  'Physicist',
  'Biologist / Botanist',
  'Writer',
  'Politician',
  'Business Owner / Entrepreneur',
  'Sportsman',
  'Actor',
  'Event Manager',
  'Journalist',
  'Media Professional',
  'Banking Professional',
  'Chartered Accountant',
  'Finance Professional',
  'Admin Professional',
  'Human Resource Professional',
  'Farming',
  'Air Hostess / Flight Attendant',
  'Piolet / Co-Piolet',
  'Architech',
  'Interior Designer',
  'Animator',
  'Web / UX Designer',
  'Beautician',
  'Hairstylist',
  'Jewellery designer'
];
String selectedWorkAs ='';